import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useAuth } from '../context/AuthContext'
import { candidate } from '../data/candidates'
import Router from 'next/router'
import { useEffect } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const {currentUser} = useAuth()

  useEffect(() => {
      if(currentUser !== null){
        Router.push({pathname: '/esd' , query: { "page": 'Search' }})
      }
  },[])
    
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
